"""Regenerate the built-in error message template and merge it into every translation.

Run after changing src/fastapi_locale/_errors_catalog.py:

    uv run python scripts/sync_error_catalog.py            # write the .pot, update the .po files
    uv run python scripts/sync_error_catalog.py --init hi  # start a new language
    uv run python scripts/sync_error_catalog.py --check    # exit 1 if anything is out of date
"""

from __future__ import annotations

import argparse
import io
import sys
from typing import TYPE_CHECKING

from babel.messages.catalog import Catalog
from babel.messages.pofile import read_po, write_po

from fastapi_locale._catalog import BUILTIN_DIRECTORY, BUILTIN_DOMAIN
from fastapi_locale._errors_catalog import TEMPLATES
from fastapi_locale._openapi import OPENAPI_CONTEXT, OPENAPI_MESSAGES

if TYPE_CHECKING:
    from pathlib import Path

TEMPLATE_PATH = BUILTIN_DIRECTORY / f"{BUILTIN_DOMAIN}.pot"
HEADER = "Built-in messages of fastapi-locale: validation errors and FastAPI's OpenAPI text."
WIDTH = 100
BUGS_ADDRESS = "https://github.com/fastapi-extensions/fastapi-locale/issues"


def build_template() -> Catalog:
    """Build the template catalog from the error template table."""
    catalog = Catalog(
        project="fastapi-locale",
        msgid_bugs_address=BUGS_ADDRESS,
        header_comment=f"# {HEADER}\n# Generated by scripts/sync_error_catalog.py; do not edit.",
        fuzzy=False,
    )
    for template in sorted(TEMPLATES.values(), key=lambda t: t.type):
        msgid = template.message if template.plural is None else (template.message, template.plural)
        catalog.add(msgid, context=template.type)
    for message in OPENAPI_MESSAGES:
        catalog.add(message, context=OPENAPI_CONTEXT)
    return catalog


def render(catalog: Catalog) -> bytes:
    """Serialize a catalog without the creation date, so output is stable."""
    buffer = io.BytesIO()
    write_po(buffer, catalog, width=WIDTH, omit_header=False, sort_output=True)
    lines = [
        line
        for line in buffer.getvalue().decode().splitlines(keepends=True)
        if not line.startswith(('"POT-Creation-Date:', '"PO-Revision-Date:'))
    ]
    return "".join(lines).encode()


def translation_paths() -> list[Path]:
    """Every built-in translation file."""
    return sorted(BUILTIN_DIRECTORY.glob(f"*/LC_MESSAGES/{BUILTIN_DOMAIN}.po"))


def updated(path: Path, template: Catalog) -> bytes:
    """Return a translation file merged with the current template."""
    locale = path.parent.parent.name
    with path.open("rb") as stream:
        catalog = read_po(stream, locale=locale, domain=BUILTIN_DOMAIN)
    catalog.update(template, no_fuzzy_matching=True)
    catalog.obsolete.clear()
    catalog.project, catalog.version = template.project, template.version
    return render(catalog)


def main() -> int:
    """Entry point."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if files are out of date")
    parser.add_argument("--init", metavar="LOCALE", help="create a translation file for LOCALE")
    args = parser.parse_args()

    template = build_template()
    outputs = {TEMPLATE_PATH: render(template)}
    if args.init:
        catalog = Catalog(
            locale=args.init,
            domain=BUILTIN_DOMAIN,
            project="fastapi-locale",
            msgid_bugs_address=BUGS_ADDRESS,
            copyright_holder="fastapi-locale contributors",
            header_comment=(
                f"# {args.init} translations for fastapi-locale.\n"
                "# Copyright (C) 2026 fastapi-locale contributors\n"
                "# This file is distributed under the same license as the fastapi-locale project."
            ),
            fuzzy=False,
        )
        catalog.update(template)
        path = BUILTIN_DIRECTORY / args.init / "LC_MESSAGES" / f"{BUILTIN_DOMAIN}.po"
        if path.exists():
            sys.stderr.write(f"{path} already exists\n")
            return 2
        outputs[path] = render(catalog)
    outputs.update({path: updated(path, template) for path in translation_paths()})

    stale = [
        path for path, data in outputs.items() if not path.exists() or path.read_bytes() != data
    ]
    if args.check:
        for path in stale:
            sys.stderr.write(f"out of date: {path}\n")
        return 1 if stale else 0
    for path in stale:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(outputs[path])
        sys.stdout.write(f"wrote {path}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
